# DATA602: Assignment 5

## Eric Lehmphul

The first step to completing this assignment is to import the Numpy package.

In [4]:
import numpy as np

## Question 1

**Create a 1D array of numbers from 0 to 9 called arr.. Desired output:
#> array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])**

In [10]:
# using np.array
arr = np.array([0,1,2,3,4,5,6,7,8,9])

print(type(arr))
arr

<class 'numpy.ndarray'>


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
# using np.arange
arr2 = np.arange(10)

print(type(arr2))
arr2

<class 'numpy.ndarray'>


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question 2

**From *arr*, extract all odd numbers.**

In [14]:
# extract function can be used to extract values that satisfy a condition
np.extract(condition = arr%2!=0, arr = arr)

array([1, 3, 5, 7, 9])

## Question 3

**Replace all even numbers in *arr* with -1.** 

In [17]:
# where function can be used to replace values that satisfy a condition
np.where(arr%2==0, -1, arr)

array([-1,  1, -1,  3, -1,  5, -1,  7, -1,  9])

## Question 4

**Convert the following 1D array to a 2D array with 2 rows.**


**Input: np.arange(10)
#> array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])**


**Desired Output:
array([[0, 1, 2, 3, 4],
[5, 6, 7, 8, 9]])**

In [20]:
# Create 1d array
arr_1d = np.arange(10)
arr_1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
# Create 2d array with reshape function
arr_2d = np.reshape(arr_1d, (2,5)) # 2 rows, 5 columns
arr_2d

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question 5

**Create a single dimension array, *array_1d*, of size n containing integers 0 to n-1.
Reshape the array. The reshaped array, *array_reshaped*, should be n/3 columns
and 3 rows.**

In [38]:
# n = 9
n = 9

# Create array_1d of size n containing 0 to n-1 values
array_1d = np.arange(n)

print("array_1d: \n", array_1d)

# Reshape array_1d to 3 rows and n/3 columns
array_reshaped = np.reshape(array_1d, (3, int((n)/3)))
print("\n array_reshaped: \n", array_reshaped)

array_1d: 
 [0 1 2 3 4 5 6 7 8]

 array_reshaped: 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [41]:
# n = 30
n = 30


# Create array_1d of size n containing 0 to n-1 values
array_1d = np.arange(n)

print("array_1d: \n", array_1d)

# Reshape array_1d to 3 rows and n/3 columns
array_reshaped = np.reshape(array_1d, (3, int((n)/3)))
print("\n array_reshaped: \n", array_reshaped)

array_1d: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

 array_reshaped: 
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]


In [42]:
# n = 87
n = 87


# Create array_1d of size n containing 0 to n-1 values
array_1d = np.arange(n)

print("array_1d: \n", array_1d)

# Reshape array_1d to 3 rows and n/3 columns
array_reshaped = np.reshape(array_1d, (3, int((n)/3)))
print("\n array_reshaped: \n", array_reshaped)

array_1d: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86]

 array_reshaped: 
 [[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24 25 26 27 28]
 [29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52
  53 54 55 56 57]
 [58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81
  82 83 84 85 86]]


## Question 6

**Create a numpy identity matrix of size n.**

In [44]:
# n = 2
n = 2
np.identity(n)

array([[1., 0.],
       [0., 1.]])

In [45]:
# n = 5
n = 5
np.identity(n)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Question 7

**Create an array filled with zeroes of size n x n (n rows, n columns).**

In [46]:
# n = 2
n = 2
np.zeros((n,n))

array([[0., 0.],
       [0., 0.]])

In [47]:
# n = 5
n = 5
np.zeros((n,n))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])